server:
    port: 8080

aerospike:
    host: localhost
    port: 3000
    namespace: test
    enabled: true

redis:
    host: localhost
    port: 6379

graphite:
    enabled: true
    host: localhost
    prefix: aerospike
    flushInterval: 10
    port: 2003

